

import { Product } from "@/model/Product";
import { Metadata } from "next";
import Link from "next/link";

export const revalidate=0;

// export async function metadata() {
//     return [
//       {
//         key: 'Cache-Control',
//         value: 'no-store, no-cache, must-revalidate, proxy-revalidate',
//       },
//     ];
//   }


  export const metadata: Metadata = {
    title: "Training App",
    description: "Generated by create next app",
    
  };

async function FetchProducts(){

    const response = await fetch("http://localhost:9000/products", {cache: 'no-store'});
    const products = await response.json() as Product[];
    console.log("Rendering FetchProducts...", products)
    console.log("Rendering FetchProducts...", new Date().toLocaleString())

    

    return (
        <div>
            <h4>Products</h4>
            <div>
                {products.map(product => {
                    return (
                        <div key={product.id}>
                            <Link href={`/server/products/${product.id}`}>{product.name}</Link>
                            
                        </div>
                    )
                })}
            </div>
        </div>
    )
}
export default FetchProducts;