import { Metadata } from "next";
import Link from "next/link";
import { cookies } from 'next/headers';

export const revalidate = 0;


export const metadata: Metadata = {
    title: "Customers",
    description: "Generated by create next app",
    
  };

async function ListCustomers(){

    // const url = `http://localhost:9000/customers?_=${new Date().getTime()}`;

    // await new Promise(resolve => setTimeout(resolve, 2000));
    // const response = await fetch(url, {cache: 'no-store'});
    // const customers =  await response.json();
    //throw new Error("SOme error happned")
    //cookies().set("my-ck", `${new Date().toLocaleString}`);


    const url = `http://localhost:3001/api/customers`;
    const response = await fetch(url, {cache: 'no-store'});
    const customers =  await response.json();
    await new Promise(resolve => setTimeout(resolve, 2000));
   
    return (
        <div>
            <h4>Customers</h4>
            {customers.map((item: any) => {
                return (
                    <div key={item.id}>
                        <p>Id: {item.id}</p>
                        <Link href={`/customers/${item.id}`}>{item.name}</Link>
                        <p>Location: {item.location}</p>
                    </div>
                )
            })}
        </div>
    )
}

export default ListCustomers;
