import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppBar from "@/components/Appbar";
import {Provider} from 'react-redux'
import { store } from "@/redux/store";
import ReduxStoreProvider from "@/redux/ReduxProvider";
import { appRoutes } from "@/routes/routes";
import { AppThemeContext, AppThemeContextProvider, initialThemeState } from "@/context/AppThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Training App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppThemeContextProvider>
        <ReduxStoreProvider>
          <AppBar routes={appRoutes}/>        
          {children}
          </ReduxStoreProvider>
        </AppThemeContextProvider>
     </body>
    </html>
  );
}
