import Link from "next/link";


//export const revalidate = 0;
export async function generateMetadata(props: {params: {id: number}}){

    const url = `http://localhost:9000/customers/${props.params.id}`;
    const response = await fetch(url, {cache: 'no-store'});
    const customer =  await response.json();

    return {
        title: "Edit Customer: " + customer.name,
        description: "Generated by create next app",
    }
}


async function EditCustomers(props: {params: {id: number}}){



    const url = `http://localhost:9000/customers/${props.params.id}`;

    await new Promise(resolve => setTimeout(resolve, 2000));
    const response = await fetch(url, {cache: 'no-store'});
    const customer =  await response.json();



    return (
        <div>
            <h4>Customers</h4>
            <div >
                        <p>Id: {customer.id}</p>
                        <p>className: {customer.name}</p>
                        <p>Location: {customer.location}</p>
            </div>
            <Link href={`/customers`}>Back</Link>
        </div>
    )
}

export default EditCustomers;
